jobs:
  - name: build-artifact
    serial: true
    plan:
      - get: omg-cli
        trigger: false
      - get: omg-product-bundle
        trigger: false
      - get: cfjump
        trigger: true
      - task: build
        file: cfjump/ci/tasks/build.yml

  - name: build-image
    serial: true
    plan:
      - get: cfjump
        passed: [ build-artifact ]
      - put: cfjump-docker
        params:
          build: cfjump/

resources:
# Output artifact first
  - name: cfjump-artifact
    type: docker-image
    source:
      repository: ramxx/cfjump
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}

# This repo itself
  - name: cfjump-gitrepo
    type: git
    source: https://github.com/RamXX/cfjump.git
    branch: master

# And now all external components I'd like to consider dependencies
# and trigger a build upon updates (not all!). They are in the order found
# in the Dockerfile.

  - name: omg-cli
    type: github-release
    check_every: 4h
    source:
      user: enaml-ops
      repository: omg-cli

  - name: omg-product-bundle
    type: github-release
    check_every: 4h
    source:
      user: enaml-ops
      repository: omg-product-bundle

  - name: cfjump
    type: github-release
    check_every: 2h
    source:
      user: ramxx
      repository: cfjump

  - name: cfjump-docker
    type: docker-image
    source:
      repository: ramxx/cfjump
      username: {{docker-username}}
      password: {{docker-password}}

